/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package zxidjava;

public class SWIGTYPE_p_zx_at_tok {
  private transient long swigCPtr;

  protected SWIGTYPE_p_zx_at_tok(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_zx_at_tok() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_zx_at_tok obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

