/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package zxidjava;

public class SWIGTYPE_p_zxid_need {
  private transient long swigCPtr;

  protected SWIGTYPE_p_zxid_need(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_zxid_need() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_zxid_need obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

