/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package zxidjava;

public class zxid_tas3_status {
  private transient long swigCPtr;

  protected zxid_tas3_status(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected zxid_tas3_status() {
    swigCPtr = 0;
  }

  protected static long getCPtr(zxid_tas3_status obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

